### ISSUE TITLE
ModuleNotFoundError: No module named 'main'

### ISSUE THREAD

**Issue by lianghuihaoking** [raffaem/cs-dlp#18]
According to the documentation, when executing the command "cs-dlp --cauth-auto chrome ........," the following error is reported:

Traceback (most recent call last):
  File "E:\Soft\anaconda3\envs\Coursera\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Soft\anaconda3\envs\Coursera\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\HouseLiang\AppData\Roaming\Python\Python39\Scripts\cs-dlp.exe\\\_\_main\_\_.py", line 4, in <module>
ModuleNotFoundError: No module named 'main'

**Comment by raffaem** [comment]
Please post the output of `git rev-parse HEAD`

**Comment by lianghuihaoking** [comment]
@raffaem hello, the result of "git rev-parse HEAD" is 4f40c9a3e9c83268cab52f273a8ff5076a838291

**Comment by raffaem** [comment]
try to reinstall it.

I think you installed from an old version

**Comment by lianghuihaoking** [comment]
@raffaem 
I uninstalled it first and then reinstalled it, but it still shows this error.

Traceback (most recent call last):
  File "E:\Soft\anaconda3\envs\Coursera\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Soft\anaconda3\envs\Coursera\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\HouseLiang\AppData\Roaming\Python\Python39\Scripts\cs-dlp.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'main'

**Comment by MuhDev** [comment]
> According to the documentation, when executing the command "cs-dlp --cauth-auto chrome ........," the following error is reported:
> 
> Traceback (most recent call last): File "E:\Soft\anaconda3\envs\Coursera\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "E:\Soft\anaconda3\envs\Coursera\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\HouseLiang\AppData\Roaming\Python\Python39\Scripts\cs-dlp.exe\__main__.py", line 4, in ModuleNotFoundError: No module named 'main'

i have the problem also
please fix it

**Comment by amjad756** [comment]
Hi, I also have the same issue and the git rev-parse HEAD ("`4f40c9a`").

**Comment by raffaem** [comment]
ok try again with the new commits

Make sure to uninstall the old versions first

```
python -m pip uninstall --yes cs-dlp
```

**Comment by amjad756** [comment]
It is working now. Thanks a lot.
