### ISSUE TITLE
Course Unsupported or Human Error

### ISSUE THREAD

**Issue by An0m0ly** [raffaem/cs-dlp#19]
Trying to download foundations-of-digital-marketing-and-e-commerce but receiving the error: 

   cs-dlp: error: unrecognized arguments: foundations-of-digital-marketing-and-e-commerce

command used that produced error: 

   cs-dlp --cauth-auto chrome foundations-of-digital-marketing-and-e-commerce

**Comment by raffaem** [comment]
WFH ...which python version are you using?

**Comment by raffaem** [comment]
Feel free to reopen it specifying the python version and the OS you are using
