### ISSUE TITLE
Not found 404

### ISSUE THREAD

**Issue by CuongVTC** [raffaem/cs-dlp#9]
The program is hanging at the last line "Not Found 404."
Is there any way to exit at this command, or do I need to restart PowerShell to continue running?
Thank you
![image](https://github.com/raffaem/cs-dlp/assets/19700387/bf8601aa-acfc-4c53-a5f0-2b5d8a138f6f)

**Comment by raffaem** [comment]
You need to provide a reproducible example

**Comment by raffaem** [comment]
Please reopen this with a MWE if it still happens
